# Don't change this! Version used to track needed updates.
version = 0
enderPearlTrail = true
snowballTrailDensity = 0.2
allayMagicDensity = 0.2
vexMagicDensity = 0.2
sheepShearFluff = true
improvedDragonFireballTrail = true
commandBlockMinecartParticles = "ON"
endCrystalParticles = true
minecartLandingSparks = true
slimeTrails = true
magmaCubeTrails = true
replaceSlimeSquishParticles = true
replaceSpellCasterParticles = true
ironGolemCrackParticles = true
spectralArrowParticles = true
wardenDeathSoulParticles = true
xpBottleParticlesDisplayType = "DEFAULT"
xpBottleParticlesDensity = 10

[attacked]
chickenFeathers = true
parrotFeathers = true
snowGolemSnowflakes = true

[sleeping]
playerSnoreChance = 1.0
playerSnoreSoundVolume = 0.25490198
playersHaveSleepingZs = false
villagerSnoreChance = 1.0
villagerSnoreSoundVolume = 1.0
villagersHaveSleepingZs = false
foxesHaveSleepingZs = false
batsHaveSleepingZs = false
catsHaveSleepingZs = false
otherMobsHaveSleepingZs = false
displaySleepingZsOnlyWhenSnoring = true
adjustNameTagWhenSleeping = false

[humanoids]
drowningBubbles = "DEFAULT"
drowningBubblesDensity = 10

[humanoids.frostyBreath]
displayType = "DEFAULT"
alpha = 0.5
waitTime = 60
seasons = "DEFAULT"
additionalBiomes = [  ]

[humanoids.player]
stomachGrowlingThreshold = 6
stomachGrowlingVolume = 1.0
heartBeatingThreshold = 6
heartbeatVolume = 1.0

[dustClouds]
scale = 0.89705884
alpha = 0.4
playerFell = true
playerRunning = false
playerRunningRequiresSpeed = false
mobFell = true
mobRunning = true
landMaceAttack = true
preventWhenRaining = false

[burning]
smoke = "DEFAULT"
flames = false
sparks = true
sounds = false

[itemRarity]
particlesDisplayType = "OFF"
particleColor = "NAME_COLOR"
mixedColorName = true
particleMaxHeight = 1.0
particleMaxSpeed = 1.0
particleDensity = 1.0

[explosives]
tntUpdateSmoke = true
tntFlames = true
tntSparks = true
creeperSmoke = "UPDATED"
creeperSparks = true